import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TARGET_FILE = path.join(__dirname, '../src/generated/buildInfo.ts');
const DIR = path.dirname(TARGET_FILE);

if (!fs.existsSync(DIR)) {
    fs.mkdirSync(DIR, { recursive: true });
}

const timestamp = Date.now();
const random = crypto.randomBytes(4).toString('hex');
const hash = crypto.createHash('sha256').update(`${timestamp}-${random}`).digest('hex').substring(0, 16);

const content = `
// Auto-generated by scripts/generate_build_info.js
export const BUILD_INFO = {
    timestamp: ${timestamp},
    hash: '${hash}',
    version: '1.0.0'
};
`;

fs.writeFileSync(TARGET_FILE, content);
console.log(`[BuildInfo] Generated build fingerprint: ${hash} at ${TARGET_FILE}`);
